classdef(Abstract) QMol_testInfo < QMol_doc
%QMol_testInfo miscellaneous information on the test suite components 
    
%   Version     Date        Author
%   01.21.000   06/17/2024  F. Mauger
%       Prepare 01.21 release


%% Documentation %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
methods (Static,Access=private)
function version
    QMol_doc.showVersion('01.21.000','06/17/2024','F. Mauger')
end
end
methods (Static,Access=?QMol_suite)
function showHeader
%showHeader displays the discretization input for the header

    fprintf('  * One-dimensional model (release)\n');
    QMol_testInfo.version;

end
function l = testList
    l                   =  {... Kernel components =========================
                            'doc',          'info',         'suite',        ...
                            'test',         'testInfo',     'Vmol',         ...
                            ... Discretization ============================
                            'disc',         'disc_basis',                   ...
                            ... DFT theory ================================
                            'DFT',          'DFT_spinPol',  'DFT_spinRes',  ...
                            'DFT_profiler',                                 ...
                            'DFT_eigs',     'DFT_eig_basis',                ...
                            'DFT_SCF_Anderson',                             ...
                            ... DFT components ============================
                            'DFT_density',  'DFT_orbital',  'DFT_orbital_basis', ...
                            'DFT_Vks',      'DFT_Vks_basis',                ...   
                            'DFT_Vks_grad',                                 ...
                            ... DFT functionals ===========================
                            'DFT_Vext',     'DFT_Vh_conv',  'DFT_Vh_fft',   ...
                            'DFT_Vx_LDA_exp',       'DFT_Vx_LDA_soft',      ...
                            'DFT_Vx_XX_conv',       'DFT_Vx_XX_fft',        ...
                            'DFT_Vc_LDA_soft',                              ...
                            ... TDDFT =====================================
                            'TDDFT',                                        ...
                            'TDDFT_sympSplitOp',        'TDDFT_SSO',        ...
                            'TDDFT_SSO_2S',             'TDDFT_SSO_4BM',    ...
                            'TDDFT_SSO_4FR',            'TDDFT_SSO_6BM',    ...
                            'TDDFT_abs_mask',           'TDDFT_abs_CAP',    ...
                            ... Schrodinger-equation theory ===============
                            'SEq',          'SE',   'SE_profiler',          ...
                            'SE_eigs',      'SE_eig_basis',                 ...
                            ... Schrodinger-equation components ===========
                            'SE_wfcn',      'SE_wfcn_basis',    'SE_V',     ...
                            ... TDSE ======================================
                            'TDSE',                                         ...
                            'TDSE_sympSplitOp',         'TDSE_SSO',         ...
                            'TDSE_SSO_2S',              'TDSE_SSO_4BM',     ...
                            'TDSE_SSO_4FR',             'TDSE_SSO_6BM',     ...
                            'TDSE_abs_mask',            'TDSE_abs_CAP',     ...
                            ... External field ============================
                            'extField_dipole',                              ...
                            ... Pseudopotentials ==========================
                            'Va_Gaussian',  'Va_softCoulomb',               ...
                            };
end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
end

