classdef(Abstract) QMol_testInfo < QMol_doc
%QMol_testInfo miscellaneous information on the test suite components 
    
%   Version     Date        Author
%   01.21.000   06/17/2024  F. Mauger
%       Prepare 01.21 release
%   01.22.000   04/19/2025  F. Mauger
%       Integrale CI module (+ new version number)
%   01.23.000   05/22/2025  F. Mauger
%       Add QMol_progressBar
%   01.23.001   05/25/2025  F. Mauger
%       Add QMol_TDCI, QMol_profiler, QMol_cte
%   01.23.002   06/04/2025  F. Mauger
%       Add QMol_TDCI_abs_CAP and QMol_TDCI_abs_mmask
%       Add QMol_TDCI_sympSplitOp and QMol_test_TDCI_SSO
%   01.23.003   06/06/2025  F. Mauger
%       Add QMol_test_TDCI_abs_CAP_space
%   01.23.004   07/22/2025  F. Mauger


%% Documentation %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
methods (Static,Access=private)
function version
    QMol_doc.showVersion('01.23.004','07/22/2025','F. Mauger')
end
end
methods (Static,Access=?QMol_suite)
function showHeader
%showHeader displays the discretization input for the header

    fprintf('  * One-dimensional model (release)\n');
    QMol_testInfo.version;

end
function l = testList
    l                   =  {... Kernel components =========================
                            'doc',          'info',         'suite',        ...
                            'test',         'cte',          'testInfo',     ...
                            'profiler',     'progressBar',  'Vmol',         ...
                            ... Discretization ============================
                            'disc',         'disc_basis',                   ...
                            ... DFT theory ================================
                            'DFT',          'DFT_spinPol',  'DFT_spinRes',  ...
                            'DFT_profiler',                                 ...
                            'DFT_eigs',     'DFT_eig_basis',                ...
                            'DFT_SCF_Anderson',                             ...
                            ... DFT components ============================
                            'DFT_density',  'DFT_orbital',  'DFT_orbital_basis', ...
                            'DFT_Vks',      'DFT_Vks_basis',                ...   
                            'DFT_Vks_grad',                                 ...
                            ... DFT functionals ===========================
                            'DFT_Vext',     'DFT_Vh_conv',  'DFT_Vh_fft',   ...
                            'DFT_Vx_LDA_exp',       'DFT_Vx_LDA_soft',      ...
                            'DFT_Vx_XX_conv',       'DFT_Vx_XX_fft',        ...
                            'DFT_Vc_LDA_soft',                              ...
                            ... TDDFT =====================================
                            'TDDFT',                                        ...
                            'TDDFT_sympSplitOp',        'TDDFT_SSO',        ...
                            'TDDFT_SSO_2S',             'TDDFT_SSO_4BM',    ...
                            'TDDFT_SSO_4FR',            'TDDFT_SSO_6BM',    ...
                            'TDDFT_extSymp',            'TDDFT_ESSO',       ...
                            'TDDFT_ESSO_2S',            'TDDFT_ESSO_4BM',   ...
                            'TDDFT_ESSO_4FR',           'TDDFT_ESSO_6BM',   ...
                            'TDDFT_abs_mask',           'TDDFT_abs_CAP',    ...
                            ... Configuration-interaction theory ==========
                            'CI',           'CI_profiler',      'CI_conv',  ...
                            ... TDCI ======================================
                            'TDCI',                                         ...
                            'TDCI_sympSplitOp',         'TDCI_SSO',         ...
                            'TDCI_SSO_2S',              'TDCI_SSO_4BM',     ...
                            'TDCI_SSO_4FR',             'TDCI_SSO_6BM',     ...
                            'TDCI_abs_CAP',             'TDCI_abs_mask',    ...
                            'TDCI_abs_CAP_space',       'TDCI_abs_mask_space', ...
                            ... Schrodinger-equation theory ===============
                            'SEq',          'SE',   'SE_profiler',          ...
                            'SE_eigs',      'SE_eig_basis',                 ...
                            ... Schrodinger-equation components ===========
                            'SE_wfcn',      'SE_wfcn_basis',    'SE_V',     ...
                            ... TDSE ======================================
                            'TDSE',                                         ...
                            'TDSE_sympSplitOp',         'TDSE_SSO',         ...
                            'TDSE_SSO_2S',              'TDSE_SSO_4BM',     ...
                            'TDSE_SSO_4FR',             'TDSE_SSO_6BM',     ...
                            'TDSE_abs_mask',            'TDSE_abs_CAP',     ...
                            ... External field ============================
                            'extField_dipole',                              ...
                            ... Pseudopotentials ==========================
                            'Va_Gaussian',  'Va_softCoulomb',               ...
                            };
end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
end

